-- swmcp.tb_coll_bill definition

CREATE TABLE `tb_coll_bill` (
  `COMP_ID` varchar(10) NOT NULL COMMENT '사업장코드',
  `SET_DATE` varchar(8) NOT NULL COMMENT '등록일자',
  `SET_SEQ` varchar(4) NOT NULL COMMENT '등록순번',
  `COLL_NUMB` varchar(30) NOT NULL COMMENT '수금번호',
  `CUST_CODE` varchar(10) DEFAULT NULL COMMENT '거래처',
  `EMP_NO` varchar(10) DEFAULT NULL COMMENT '담당자',
  `DEPT_CODE` varchar(10) DEFAULT NULL COMMENT '담당부서',
  `SALES_KIND` bigint(20) DEFAULT NULL COMMENT '매출구분',
  `COLL_KIND` bigint(20) DEFAULT NULL COMMENT '수금구분',
  `RACE_KIND` bigint(20) DEFAULT NULL COMMENT '수금방법',
  `BILL_TYPE` bigint(20) DEFAULT NULL COMMENT '어음구분',
  `MNY_EA` bigint(20) DEFAULT NULL COMMENT '화폐단위',
  `MNY_RATE` decimal(16,4) DEFAULT 1.0000 COMMENT '환율',
  `EXCH_GAP` decimal(16,4) DEFAULT 0.0000 COMMENT '환차',
  `COMMISSION` decimal(16,4) DEFAULT 0.0000 COMMENT '수수료',
  `MANAGE_NO` varchar(30) DEFAULT NULL COMMENT '번호(통장/어음/카드)',
  `APP_NO` varchar(30) DEFAULT NULL COMMENT '승인번호',
  `BAL_DATE` varchar(8) DEFAULT NULL COMMENT '발행일',
  `END_DATE` varchar(8) DEFAULT NULL COMMENT '만기일',
  `BAL_CUST_NM` varchar(50) DEFAULT NULL COMMENT '발행인',
  `BAL_BANK_NM` varchar(50) DEFAULT NULL COMMENT '발행은행',
  `COLL_AMT` decimal(16,4) DEFAULT NULL COMMENT '수금금액',
  `SLIP_NUMB` varchar(30) DEFAULT NULL COMMENT '전표번호',
  `RMKS` varchar(100) DEFAULT NULL COMMENT '특이사항',
  `TEMP1` varchar(10) DEFAULT NULL COMMENT '임시01',
  `TEMP2` varchar(10) DEFAULT NULL COMMENT '임시02',
  `TEMP3` varchar(10) DEFAULT NULL COMMENT '임시03',
  `TEMP4` varchar(10) DEFAULT NULL COMMENT '임시04',
  `TEMP5` varchar(10) DEFAULT NULL COMMENT '임시05',
  `SYS_EMP_NO` varchar(10) NOT NULL COMMENT '등록사번',
  `SYS_ID` varchar(30) NOT NULL COMMENT '등록ID',
  `SYS_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '등록일자',
  `UPD_EMP_NO` varchar(10) DEFAULT NULL COMMENT '수정사번',
  `UPD_ID` varchar(30) DEFAULT NULL COMMENT '수정ID',
  `UPD_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '수정일자',
  PRIMARY KEY (`COMP_ID`,`COLL_NUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='수금관리';