CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_QUAL026$GET_USE_DEPT`(	
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin
	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 


	SELECT 
			A.DATA_ID,
			A.PARENT,
			A.DEPT_CODE,
			A.DEPT_NAME
	  FROM  DEPT_CODE A
	 WHERE 	A.DELETE_YN = 'N'
	   and  A.USE_YN = 'Y'
   ;
	
	SET N_RETURN = 0;
    SET V_RETURN = '조회되었습니다.'; 
end