-- swmcp.tb_msur_equi definition

CREATE TABLE `tb_msur_equi` (
  `COMP_ID` varchar(10) NOT NULL COMMENT '사업장코드',
  `EQUI_CODE` varchar(20) NOT NULL COMMENT '관리번호',
  `CLASS1` bigint(20) NOT NULL COMMENT '대분류',
  `CLASS2` bigint(20) NOT NULL COMMENT '중분류',
  `TEMP_SEQ` varchar(3) NOT NULL COMMENT '순번',
  `EQUI_NAME` varchar(50) DEFAULT NULL COMMENT '검사장비명',
  `EQUI_SPEC` varchar(200) DEFAULT NULL COMMENT '규격',
  `EQUI_NUM` varchar(20) DEFAULT NULL COMMENT '기기번호',
  `MAKE_COMP` varchar(50) DEFAULT NULL COMMENT '규격',
  `MODEL_NAME` varchar(50) DEFAULT NULL COMMENT '모델명',
  `BUY_AMT` decimal(16,2) DEFAULT 0.00 COMMENT '구입가격',
  `BUY_COMP` varchar(50) DEFAULT NULL COMMENT '구입처',
  `BUY_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '구입일자',
  `USE_DEPT` varchar(10) DEFAULT NULL COMMENT '사용부서',
  `ETC_RMK` varchar(200) DEFAULT NULL COMMENT '비고',
  `BUY_POST_NO` varchar(10) DEFAULT NULL COMMENT '구입처주소_우편번호',
  `BUY_ADDRESS` varchar(100) DEFAULT NULL COMMENT '구입처주소',
  `BUY_PHONE` varchar(20) DEFAULT NULL COMMENT '구입처전화번호',
  `RES_STATUS` bigint(20) DEFAULT NULL COMMENT '자원상태',
  `USE_EMP` varchar(20) DEFAULT NULL COMMENT '담당자',
  `BUY_EMAIL` varchar(50) DEFAULT NULL COMMENT '구입처이메일',
  `PREV_EQUI_CODE` varchar(20) NOT NULL COMMENT '이전관리번호',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '파일명',
  `REAL_FILE_NAME` varchar(100) DEFAULT NULL COMMENT '실제파일명',
  `TEMP1` varchar(10) DEFAULT NULL COMMENT '임시01',
  `TEMP2` varchar(10) DEFAULT NULL COMMENT '임시02',
  `TEMP3` varchar(10) DEFAULT NULL COMMENT '임시03',
  `TEMP4` varchar(10) DEFAULT NULL COMMENT '임시04',
  `TEMP5` varchar(10) DEFAULT NULL COMMENT '임시05',
  `SYS_EMP_NO` varchar(10) NOT NULL COMMENT '등록사번',
  `SYS_ID` varchar(30) NOT NULL COMMENT '등록ID',
  `SYS_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '등록일자',
  `UPD_EMP_NO` varchar(10) DEFAULT NULL COMMENT '수정사번',
  `UPD_ID` varchar(30) DEFAULT NULL COMMENT '수정ID',
  `UPD_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '수정일자',
  PRIMARY KEY (`COMP_ID`,`EQUI_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='검사장비';