CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_QUAL029$DELETE_MSUR_EQUICHECK`(		
	IN A_COMP_ID varchar(10),
	IN A_EQUI_CODE varchar(20),
	IN A_IDX int(11),
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 

	SET N_RETURN = 0;
  	SET V_RETURN = '저장되었습니다.'; 
  
   DELETE FROM TB_MSUR_EQUICHECK_RESULT
	 WHERE COMP_ID = A_COMP_ID
	   AND IDX = A_IDX
	   AND EQUI_CODE = A_EQUI_CODE
	 ;
	
	IF ROW_COUNT() = 0 THEN
  	  SET N_RETURN = -1;
      SET V_RETURN = '저장이 실패하였습니다.'; 
  	END IF;  
  
end