-- swmcp.tb_stock_move definition

CREATE TABLE `tb_stock_move` (
  `COMP_ID` varchar(10) NOT NULL COMMENT '사업장코드',
  `SET_DATE` varchar(8) NOT NULL COMMENT '등록일자',
  `SET_SEQ` varchar(4) NOT NULL COMMENT '등록순번',
  `SET_NO` varchar(4) NOT NULL COMMENT 'NO',
  `MOVE_KEY` varchar(30) NOT NULL COMMENT '창고이동KEY',
  `MOVE_DATE` varchar(8) NOT NULL COMMENT '이동일자',
  `ITEM_CODE` varchar(20) NOT NULL COMMENT '품목코드',
  `LOT_NO` varchar(30) NOT NULL COMMENT 'LOT NO',
  `QTY` decimal(10,0) DEFAULT 0 COMMENT '수량',
  `COST` decimal(16,4) DEFAULT 0.0000 COMMENT '단가',
  `AMT` decimal(16,4) DEFAULT 0.0000 COMMENT '금액',
  `WARE_CODE` bigint(20) DEFAULT NULL COMMENT '이동창고코드',
  `WARE_CODE_PRE` bigint(20) DEFAULT NULL COMMENT '이동창고코드',
  `ITEM_KIND` varchar(10) DEFAULT NULL COMMENT '품목구분',
  `CONFIRM_YN` varchar(1) DEFAULT 'N' COMMENT '이동확정',
  `CONFIRM_EMP` varchar(10) DEFAULT NULL COMMENT '이동확정사번',
  `CONFIRM_DT` timestamp NULL DEFAULT current_timestamp() COMMENT '이동확정일시',
  `RMK` varchar(100) DEFAULT NULL COMMENT '비고',
  `TEMP1` varchar(10) DEFAULT NULL COMMENT '임시01',
  `TEMP2` varchar(10) DEFAULT NULL COMMENT '임시02',
  `TEMP3` varchar(10) DEFAULT NULL COMMENT '임시03',
  `TEMP4` varchar(10) DEFAULT NULL COMMENT '임시04',
  `TEMP5` varchar(10) DEFAULT NULL COMMENT '임시05',
  `SYS_EMP_NO` varchar(10) NOT NULL COMMENT '등록사번',
  `SYS_ID` varchar(30) NOT NULL COMMENT '등록ID',
  `SYS_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '등록일자',
  `UPD_EMP_NO` varchar(10) DEFAULT NULL COMMENT '수정사번',
  `UPD_ID` varchar(30) DEFAULT NULL COMMENT '수정ID',
  `UPD_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '수정일자',
  PRIMARY KEY (`COMP_ID`,`MOVE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='창고이동관리';