CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_MOLD009$UPDATE_MOLD_STOCK_WARE_POS`(	
	IN A_COMP_ID varchar(10),
	IN A_RACK_CODE varchar(20),
	IN A_WARE_CODE bigint(20),
	IN A_MOLD_CODE varchar(30),
	IN A_LOT_NO varchar(30),
	IN A_UPD_EMP_NO varchar(10),
	IN A_UPD_ID varchar(30),
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin

	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 

	SET N_RETURN = 0;
  	SET V_RETURN = '저장되었습니다.'; 
  
	UPDATE TB_MOLD_STOCK
		SET 
	    	WARE_POS = A_RACK_CODE
	    	,WARE_POS_DATE = SYSDATE()
	    	,UPD_EMP_NO = A_UPD_EMP_NO
	    	,UPD_ID = A_UPD_ID
	    	,UPD_DATE = SYSDATE()
	 WHERE COMP_ID = A_COMP_ID
	   and WARE_CODE = A_WARE_CODE
	   AND MOLD_CODE = A_MOLD_CODE
	   AND LOT_NO = A_LOT_NO
	 ;
	
	select COUNT(*) as CNT
	from TB_MOLD_STOCK
	WHERE COMP_ID = A_COMP_ID
	   and WARE_CODE = A_WARE_CODE
	   AND MOLD_CODE = A_MOLD_CODE
	   AND LOT_NO = A_LOT_NO
	   and WARE_POS = A_RACK_CODE
	 ;
	
	IF ROW_COUNT() = 0 THEN
  	  SET N_RETURN = -1;
      SET V_RETURN = '저장이 실패하였습니다.'; 
  	END IF;  
  
end