CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_PURC110$GET_DEPT_WARE`(	
	IN A_COMP_ID varchar(10),
	IN A_DEPT_CODE varchar(10),
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin

	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 


	select WARE_CODE as WARE_CODE
	from DEPT_CODE
	where DEPT_CODE = A_DEPT_CODE
	;
	

	set N_RETURN := 0;
    set V_RETURN := '조회 되었습니다';
END