CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_ACNT035$GET_RECEIVABLE_BILL_MAIN`(
	IN A_COMP_ID varchar(10),
	IN A_ST_DATE DATETIME,
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin
	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 
   
    create temporary table if not exists TMP_ACNT035_GET_RECEIVABLE_BILL_MAIN
  (COLL_DATE VARCHAR(20),
	END_DATE VARCHAR(20),
	CUST_CODE VARCHAR(20),
	CUST_NAME VARCHAR(100),
	BILL_NO VARCHAR(20),
	BILL_AMT DECIMAL(16,4),
	BILL_TYPE VARCHAR(20),
	BAL_DATE VARCHAR(20),
	BAL_CUST_NM VARCHAR(100),
	REMARKS  VARCHAR(100)); 
 
	call FN_ACNT_AC_END_DATE_PRIOR (A_COMP_ID, date_format(A_ST_DATE, '%Y%m%d'), @pFY, @pFROM_DATE, @pTO_DATE);
	
   DELETE FROM TMP_ACNT035_GET_RECEIVABLE_BILL_MAIN;
   
   INSERT INTO TMP_ACNT035_GET_RECEIVABLE_BILL_MAIN
    SELECT B.COLL_DATE,
           B.END_DATE,
           B.CUST_CODE,
           FN_CUST_NAME(A_COMP_ID, B.CUST_CODE) AS CUST_NAME,
           B.BILL_NO,
           SUM(A.DR_AMT - A.CR_AMT) AS BILL_AMT,
           FN_USE_CODE_NAME(B.COMP_ID, 'B08' , B.BILL_TYPE) AS BILL_TYPE,
           B.BAL_DATE,
           B.BAL_CUST_NM,
           '' AS REMARKS
    FROM VEW_SLIP_ALL A, TBL_BILLS_RECEIVABLE B
    WHERE A.COMP_ID = A_COMP_ID
    AND A.APPL_DATE > @pTO_DATE AND A.APPL_DATE <= date_format(A_ST_DATE, '%Y%m%d')
    AND A.CHK_KIND IN ('1','2')
    AND RTRIM(A.AC_NO) LIKE B.BILL_NO
    GROUP BY B.COLL_DATE, B.END_DATE, B.CUST_CODE, B.BILL_NO, B.BILL_TYPE, B.BAL_DATE, B.BAL_CUST_NM, FN_CUST_NAME(A_COMP_ID, B.CUST_CODE),FN_USE_CODE_NAME(B.COMP_ID, 'B08' , B.BILL_TYPE)
    HAVING     SUM(A.DR_AMT-A.CR_AMT)>0;
   
        SELECT '1' AS SORT, COLL_DATE, END_DATE, CUST_CODE, CUST_NAME, BILL_NO, BILL_AMT, BILL_TYPE, BAL_DATE, BAL_CUST_NM, REMARKS
        FROM TMP_ACNT035_GET_RECEIVABLE_BILL_MAIN
        
        UNION ALL
        
        SELECT '2' AS SORT, '', '', '', '합  계', '', SUM(BILL_AMT), '', '', '', ''
        FROM TMP_ACNT035_GET_RECEIVABLE_BILL_MAIN;
    
   
	SET N_RETURN = 0;
    SET V_RETURN = '조회되었습니다.';
  
end