CREATE DEFINER=`root`@`%` PROCEDURE `swmcp`.`PKG_PURC108$GET_INPUT_RETURN_LIST_POP`(
			IN A_ST_DATE 			TIMESTAMP,
			IN A_ED_DATE			TIMESTAMP,
            OUT N_RETURN      	INT,
            OUT V_RETURN      	VARCHAR(4000)
)
PROC:begin
	
	declare exit HANDLER for sqlexception
	call USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 

	select
		  STR_TO_DATE(A.SET_DATE, '%Y%m%d') as SET_DATE,
		  A.SET_SEQ,
		  A.INPUT_RETURN_MST_KEY,
		  STR_TO_DATE(A.RETURN_DATE, '%Y%m%d') as RETURN_DATE,
		  A.CUST_CODE,
		  C.CUST_NAME,
		  B.ITEM_CODE,
		  D.ITEM_NAME,
		  D.ITEM_SPEC,
		  B.QTY,
		  B.COST,
		  B.AMT,
		  SUM(DET.QTY) as RETURN_QTY,
		  A.EMP_NO,
		  E.KOR_NAME as EMP_NAME,
		  A.DEPT_CODE,
		  A.SHIP_INFO,
		  A.PJ_NO,
		  A.PJ_NAME,
		  A.RMKS
	from TB_INPUT_RETURN_MST A
		inner join TB_INPUT_RETURN_DET DET	
			on A.COMP_ID = DET.COMP_ID 
			and A.INPUT_RETURN_MST_KEY = DET.INPUT_RETURN_MST_KEY 
		inner join TB_INPUT_MST B
			on A.CUST_CODE = B.CUST_CODE
			and A.SHIP_INFO = B.SHIP_INFO
			and A.PJ_NO = B.PJ_NO
			and A.ITEM_KIND = B.ITEM_KIND
		inner join TC_CUST_CODE C
			on A.COMP_ID = C.COMP_ID
			and A.CUST_CODE = C.CUST_CODE
		LEFT join TB_ITEM_CODE D
			on B.ITEM_CODE = D.ITEM_CODE
		LEFT join INSA_MST E
			on A.COMP_ID = E.COMP_ID
			and A.EMP_NO = E.KOR_NAME
	where A.SET_DATE BETWEEN DATE_FORMAT(A_ST_DATE, '%Y%m%d') and DATE_FORMAT(A_ED_DATE, '%Y%m%d')
	;

	set N_RETURN := 0;
    set V_RETURN := '조회 되었습니다';
END