CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_DIST005$DELETE_RACK_CODE`(	
	IN A_COMP_ID varchar(10),
	IN A_RACK_CODE varchar(20),
	IN A_RACK_NAME varchar(30),
	IN A_RACK_DIV bigint(20),
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin

	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 

	SET N_RETURN = 0;
  	SET V_RETURN = '삭제되었습니다.'; 
  
	DELETE FROM TB_RACK
	WHERE COMP_ID = A_COMP_ID
	   AND RACK_CODE = A_RACK_CODE
	   AND RACK_NAME = A_RACK_NAME
	   AND RACK_DIV = A_RACK_DIv
	;
	
	IF ROW_COUNT() = 0 THEN
  	  SET N_RETURN = -1;
      SET V_RETURN = '삭제에 실패하였습니다.'; 
  	END IF;  
  
end