-- swmcp.tb_coating_work definition

CREATE TABLE `tb_coating_work` (
  `COMP_ID` varchar(10) NOT NULL COMMENT '사업장코드',
  `WORK_LINE` varchar(10) DEFAULT NULL COMMENT '생산라인',
  `SET_DATE` varchar(8) NOT NULL COMMENT '등록일자',
  `SET_SEQ` varchar(3) NOT NULL COMMENT '등록순번',
  `SET_NO` varchar(3) NOT NULL COMMENT 'NO',
  `WORK_KEY` varchar(30) NOT NULL COMMENT '생산KEY (MC + 년월(4) + 순번(3) + NO(3))',
  `WORK_DATE` varchar(8) NOT NULL COMMENT '생산일자',
  `MATR_CODE` varchar(30) NOT NULL COMMENT '품목코드',
  `PROG_CODE` varchar(10) DEFAULT NULL COMMENT '공정코드',
  `EQUI_CODE` varchar(10) DEFAULT NULL COMMENT '설비',
  `ORDER_KEY` varchar(30) DEFAULT NULL COMMENT '주문번호',
  `WORK_PLAN_KEY` varchar(50) NOT NULL COMMENT '생산계획 KEY',
  `LOT_NO` varchar(30) NOT NULL COMMENT '개별 LOT NO',
  `PLAN_QTY` decimal(16,4) DEFAULT 0.0000 COMMENT '계획수량',
  `WORK_QTY` decimal(16,4) DEFAULT 0.0000 COMMENT '생산수량(불량수량포함)',
  `BAD_QTY` decimal(16,4) DEFAULT 0.0000 COMMENT '불량수량',
  `START_TIME` timestamp NULL DEFAULT NULL COMMENT '생산시작시간',
  `END_TIME` timestamp NULL DEFAULT NULL COMMENT '생산종료시간',
  `SHIP_INFO` varchar(30) DEFAULT NULL COMMENT '호선정보',
  `WORK_DEPT` varchar(10) DEFAULT NULL COMMENT '생산부서코드',
  `WORK_EMP` varchar(10) DEFAULT NULL COMMENT '생산담당자',
  `WARE_CODE` bigint(20) DEFAULT NULL COMMENT '재고창고 (cfg.com.wh.kind)',
  `RMK` varchar(100) DEFAULT NULL COMMENT '비고',
  `SYS_EMP_NO` varchar(10) DEFAULT NULL,
  `SYS_ID` decimal(10,0) DEFAULT NULL,
  `SYS_DATE` timestamp NULL DEFAULT NULL,
  `UPD_EMP_NO` varchar(10) DEFAULT NULL,
  `UPD_ID` decimal(10,0) DEFAULT NULL,
  `UPD_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`COMP_ID`,`WORK_KEY`),
  UNIQUE KEY `tb_coating_work_unique` (`COMP_ID`,`WORK_LINE`,`SET_DATE`,`SET_SEQ`,`SET_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='코팅생산실적관리';