CREATE DEFINER=`root`@`%` PROCEDURE `swmcp`.`PKG_PROD035$GET_COATING_PLAN_DET`(	
	in A_COMP_ID VARCHAR(10),
	IN A_MATR_LOT_NO	varchar(30),
	in A_WORK_LINE	VARCHAR(10),
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin
	
	declare V_SET_DATE	VARCHAR(8);

	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 


		select
			  A.COMP_ID,
			  A.MATR_LOT_NO,
			  A.SET_SEQ,
-- 			  STR_TO_DATE(A.PLAN_DATE, '%Y%m%d') as PLAN_DATE,
			  A.PLAN_DATE,
			  A.PLAN_MST_KEY,
			  A.WORK_PLAN_KEY,
			  A.WORK_LINE,
			  A.MATR_CODE,
			  A.PROG_CODE,
			  A.PLAN_QTY,
			  A.DEPT_CODE,
			  A.CONFIRM_YN,
			  A.WORK_QTY,
			  A.END_YN,
			  A.RMK
		from TB_COATING_PLAN_DET A 
		where A.COMP_ID = A_COMP_ID
		  and A.MATR_LOT_NO = A_MATR_LOT_NO
		  and A.WORK_LINE = A_WORK_LINE
		;
		 
		
	SET N_RETURN = 0;
    SET V_RETURN = '조회되었습니다.';
   
END