-- swmcp.tb_mold_subul definition

CREATE TABLE `tb_mold_subul` (
  `COMP_ID` varchar(10) NOT NULL COMMENT '사업장코드',
  `KEY_VAL` varchar(100) NOT NULL COMMENT '수불KEY',
  `IO_DATE` varchar(8) NOT NULL COMMENT '수불일자',
  `IN_OUT` varchar(1) NOT NULL COMMENT '입/출고 (입:1, 출:2)',
  `WARE_CODE` varchar(10) DEFAULT NULL COMMENT '창고코드',
  `MOLD_CODE` varchar(30) NOT NULL COMMENT '금형코드',
  `LOT_NO` varchar(30) NOT NULL COMMENT 'LOT NO',
  `IO_GUBN` varchar(10) DEFAULT NULL COMMENT '입출내역구분',
  `IO_QTY` decimal(16,4) DEFAULT 0.0000 COMMENT '수량/중량',
  `IO_PRC` decimal(16,4) DEFAULT 0.0000 COMMENT '단가',
  `IO_AMT` decimal(16,4) DEFAULT 0.0000 COMMENT '금액',
  `TABLE_NAME` varchar(50) DEFAULT NULL COMMENT '테이블명',
  `TABLE_KEY` varchar(100) DEFAULT NULL COMMENT '테이블KEY',
  `STOCK_YN` varchar(1) DEFAULT 'Y' COMMENT '재고반영여부',
  `CUST_CODE` varchar(10) DEFAULT NULL COMMENT '거래처',
  `TEMP1` varchar(10) DEFAULT NULL COMMENT '임시01',
  `TEMP2` varchar(10) DEFAULT NULL COMMENT '임시02',
  `TEMP3` varchar(10) DEFAULT NULL COMMENT '임시03',
  `TEMP4` varchar(10) DEFAULT NULL COMMENT '임시04',
  `TEMP5` varchar(10) DEFAULT NULL COMMENT '임시05',
  `SYS_EMP_NO` varchar(10) NOT NULL COMMENT '등록사번',
  `SYS_ID` varchar(30) NOT NULL COMMENT '등록ID',
  `SYS_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '등록일자',
  `UPD_EMP_NO` varchar(10) DEFAULT NULL COMMENT '수정사번',
  `UPD_ID` varchar(30) DEFAULT NULL COMMENT '수정ID',
  `UPD_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '수정일자',
  PRIMARY KEY (`COMP_ID`,`KEY_VAL`,`LOT_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='금형수불';