CREATE DEFINER=`ubidom`@`%` PROCEDURE `swmcp`.`PKG_QUAL026$UPDATE_MSUR_EQUICHECK`(		
	IN A_COMP_ID varchar(10),
	IN A_IDX int(11),
	IN A_EQUI_CODE varchar(20),
	IN A_CHECK_ITEM varchar(10),
	IN A_CYCLE decimal(3, 0),
	IN A_FINAL_DATE timestamp,
	IN A_CHECK_DEPT varchar(10),
	IN A_ETC_RMK varchar(200),
	IN A_UPD_EMP_NO varchar(10),
	IN A_UPD_ID varchar(30),
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin
	
	declare V_NEXT_DATE timestamp;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 

	SET N_RETURN = 0;
  	SET V_RETURN = '저장되었습니다.'; 
  
   set V_NEXT_DATE = DATE_ADD(A_FINAL_DATE, interval A_CYCLE MONTH);
  
   UPDATE TB_MSUR_EQUICHECK
		SET 
	    	CHECK_ITEM = A_CHECK_ITEM
	    	,CYCLE = A_CYCLE
	    	,FINAL_DATE = DATE_FORMAT(A_FINAL_DATE, '%Y%m%d')
	    	,NEXT_DATE = DATE_FORMAT(V_NEXT_DATE, '%Y%m%d')
	    	,CHECK_DEPT = A_CHECK_DEPT
	    	,ETC_RMK = A_ETC_RMK
	    	,UPD_EMP_NO = A_UPD_EMP_NO
	    	,UPD_ID = A_UPD_ID
	    	,UPD_DATE = SYSDATE()
	 WHERE COMP_ID = A_COMP_ID
	   AND EQUI_CODE = A_EQUI_CODE
	   AND IDX = A_IDX
	 ;
	
	IF ROW_COUNT() = 0 THEN
  	  SET N_RETURN = -1;
      SET V_RETURN = '저장이 실패하였습니다.'; 
  	END IF;  
  
end