CREATE DEFINER=`root`@`%` PROCEDURE `swmcp`.`PKG_SALE010$GET_TAX_DET`(	
	IN A_COMP_ID VARCHAR(10),
	IN A_TAX_NUMB VARCHAR(30),
	IN A_ST_DATE TIMESTAMP,
	IN A_ED_DATE TIMESTAMP,
	IN A_CREATE_YN VARCHAR(10), -- 생성구분 생성 미생성
	IN A_SALES_KIND VARCHAR(10), -- 매출구분 내수 1 수출 2
	IN A_END_GUBUN VARCHAR(10), -- 합산마감 0 /개별마감 1
	IN A_CUST_CODE VARCHAR(300), -- 거래처
	IN A_MASETR_KEY VARCHAR(50),
	IN A_DIV_MST VARCHAR(30),
	IN A_SEARCH VARCHAR(10),
	
	OUT N_RETURN INT,
	OUT V_RETURN VARCHAR(4000)
	)
begin
	DECLARE EXIT HANDLER FOR SQLEXCEPTION 
	CALL USP_SYS_GET_ERRORINFO_ALL(V_RETURN, N_RETURN); 
	
	-- 리텍의 PKG_SALE_TAX.GET_TAX_D 참조

	select
		  A.COMP_ID
		  ,A.TAX_NUMB
		  ,A.TAX_SEQ
		  ,STR_TO_DATE(A.ACT_DATE, '%Y%m%d') as ACT_DATE
		  ,B.CUST_CODE
		  ,B.EMP_NO
		  ,B.DEPT_CODE
		  ,A.ITEM_CODE
		  ,A.QTY
		  ,A.COST
		  ,A.SUPP_AMT
		  ,A.VAT
		  ,A.CALL_KIND
		  ,A.CALL_KEY
		  ,A.DIFF_AMT
		  ,A.RMK
	from TB_TAX_DET A
		inner join TB_TAX_MST B 
			on (A.COMP_ID = B.COMP_ID
			and A.TAX_NUMB = B.TAX_NUMB)
		inner join TC_CUST_CODE C 
			on (A.COMP_ID = C.COMP_ID
			and B.CUST_CODE = C.CUST_CODE)
		inner join TB_ITEM_CODE I
			on (A.ITEM_CODE = I.ITEM_CODE)
	where A.COMP_ID = A_COMP_ID
	  and A.TAX_NUMB = A_TAX_NUMB
	;
	
	SET N_RETURN = 0;
    SET V_RETURN = '조회되었습니다.';
end