-- swmcp.tb_mold_modi definition

CREATE TABLE `tb_mold_modi` (
  `COMP_ID` varchar(10) NOT NULL COMMENT '사업장코드',
  `SET_DATE` varchar(8) NOT NULL COMMENT '등록일자',
  `SET_SEQ` varchar(4) NOT NULL COMMENT '등록순번',
  `SET_NO` varchar(4) NOT NULL COMMENT 'NO',
  `MOLD_MODI_KEY` varchar(30) NOT NULL COMMENT '금형수리번호',
  `MODI_DIV` varchar(10) DEFAULT NULL COMMENT '수리(R)/수정(M)구분',
  `MOLD_CODE` varchar(20) NOT NULL COMMENT '금형코드',
  `CUST_CODE` varchar(10) DEFAULT NULL COMMENT '거래처',
  `IN_OUT` varchar(10) DEFAULT NULL COMMENT '처리주최(사내(IN)/사외(OUT))',
  `QTY` decimal(10,0) DEFAULT 0 COMMENT '수량',
  `LOT_NO` varchar(30) DEFAULT NULL COMMENT 'LOT NO',
  `COST` decimal(16,4) DEFAULT 0.0000 COMMENT '단가',
  `AMT` decimal(16,4) DEFAULT 0.0000 COMMENT '금액',
  `MOLD_CODE_AFT` varchar(30) DEFAULT NULL COMMENT '수정후금형코드',
  `LOT_NO_AFT` varchar(30) DEFAULT NULL COMMENT '수정후 LOT NO',
  `EMP_NO` varchar(10) DEFAULT NULL COMMENT '담당자',
  `DEPT_CODE` varchar(10) DEFAULT NULL COMMENT '담당부서',
  `CONT` varchar(100) DEFAULT NULL COMMENT '수리내용',
  `RMK` varchar(100) DEFAULT NULL COMMENT '비고',
  `TEMP1` varchar(10) DEFAULT NULL COMMENT '임시01',
  `TEMP2` varchar(10) DEFAULT NULL COMMENT '임시02',
  `TEMP3` varchar(10) DEFAULT NULL COMMENT '임시03',
  `TEMP4` varchar(10) DEFAULT NULL COMMENT '임시04',
  `TEMP5` varchar(10) DEFAULT NULL COMMENT '임시05',
  `SYS_EMP_NO` varchar(10) NOT NULL COMMENT '등록사번',
  `SYS_ID` varchar(30) NOT NULL COMMENT '등록ID',
  `SYS_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '등록일자',
  `UPD_EMP_NO` varchar(10) DEFAULT NULL COMMENT '수정사번',
  `UPD_ID` varchar(30) DEFAULT NULL COMMENT '수정ID',
  `UPD_DATE` timestamp NULL DEFAULT current_timestamp() COMMENT '수정일자',
  PRIMARY KEY (`COMP_ID`,`MOLD_MODI_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='금형수리수정관리';